// examples/vue/src/App.vue
<script setup lang="ts">
import { reactive } from 'vue';
import { useJitForm } from '@jitforms/vue';

const { submit, isLoading, isSuccess, isError, fieldError, submission, reset } = useJitForm('Jve1ZElW', {
  baseUrl: 'https://jitforms.test',
  honeypot: true,
});

const form = reactive({ name: '', email: '', message: '' });

async function onSubmit(e: Event) {
  e.preventDefault();
  await submit({ ...form });
}
</script>

<template>
  <template v-if="isSuccess">
    <div class="success">✓ Submitted successfully.</div>
    <pre style="font-size:0.75rem;overflow:auto">{{ JSON.stringify(submission, null, 2) }}</pre>
    <button @click="reset">Submit again</button>
  </template>
  <form v-else @submit="onSubmit">
    <div v-if="isError" class="fail">Something went wrong.</div>
    <div>
      <label for="name">Name</label>
      <input id="name" v-model="form.name" />
      <div v-if="fieldError('name')" class="error">{{ fieldError('name') }}</div>
    </div>
    <div>
      <label for="email">Email</label>
      <input id="email" v-model="form.email" type="email" />
      <div v-if="fieldError('email')" class="error">{{ fieldError('email') }}</div>
    </div>
    <div>
      <label for="message">Message</label>
      <textarea id="message" v-model="form.message"></textarea>
      <div v-if="fieldError('message')" class="error">{{ fieldError('message') }}</div>
    </div>
    <button type="submit" :disabled="isLoading">{{ isLoading ? 'Sending…' : 'Send' }}</button>
  </form>
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { createJitForm } from '@jitforms/svelte';

  const form = createJitForm({
    baseUrl: 'https://jitforms.test',
    formHash: 'Jve1ZElW',
    honeypot: true,
  });

  let name = $state('');
  let email = $state('');
  let message = $state('');

  async function onSubmit(e: Event) {
    e.preventDefault();
    await $form.submit({ name, email, message });
  }
</script>

{#if $form.isSuccess}
  <div class="success">✓ Submitted successfully.</div>
  <pre style="font-size:0.75rem;overflow:auto">{JSON.stringify($form.submission, null, 2)}</pre>
  <button onclick={() => $form.reset()}>Submit again</button>
{:else}
  <form onsubmit={onSubmit}>
    {#if $form.isError}
      <div class="fail">Something went wrong.</div>
    {/if}
    <div>
      <label for="name">Name</label>
      <input id="name" bind:value={name} />
      {#if $form.fieldError('name')}<div class="error">{$form.fieldError('name')}</div>{/if}
    </div>
    <div>
      <label for="email">Email</label>
      <input id="email" type="email" bind:value={email} />
      {#if $form.fieldError('email')}<div class="error">{$form.fieldError('email')}</div>{/if}
    </div>
    <div>
      <label for="message">Message</label>
      <textarea id="message" bind:value={message}></textarea>
      {#if $form.fieldError('message')}<div class="error">{$form.fieldError('message')}</div>{/if}
    </div>
    <button type="submit" disabled={$form.isLoading}>
      {$form.isLoading ? 'Sending…' : 'Send'}
    </button>
  </form>
{/if}
